# -*- coding: utf-8 -*-
"""Aakash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJv2AviVP-ttudckVU9aQmZtB28Y83r0
"""

import numpy as np
from PIL import Image
from google.colab import files
from io import BytesIO

upload = files.upload()

import matplotlib.pyplot as plt
im = Image.open("rose.jpeg")
plt.imshow(im)
plt.show()

im = Image.open("rose.jpeg")
im=np.array(im) #conv image to array
row, col, color = im.shape 

for i in range(row):
    for j in range(col):
        #print(im[i][j])
        if im[i][j][0] > 250:   #0=red,1=green,2=blue
            im[i][j] = ( im[i,j,0] //3 + im[i,j,1] //3 + im[i,j,2]//3)
        elif im [i][j][1] < 35  or im[i][j][2] <35:
            im[i][j] =  ( im[i,j,0] //3 + im[i,j,1] //3 + im[i,j,2]//3)
# if red>150 and b&g<50 the we will get red colour.... so we blackes all colours except red
        else :
            pass
            
im2=Image.fromarray(im)  #conv array to image 
im2.save("only_red.jpg")

plt.imshow(im2)
plt.show()